name: Build

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.BUILDER_APP_ID }}
          private-key: ${{ secrets.BUILDER_APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Build and push
        uses: docker/bake-action@v5
        with:
          source: "${{ github.server_url }}/${{ secrets.SCRIPT_REPO }}.git#main"
          push: true
          github-token: ${{ steps.generate-token.outputs.token }}
